version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: primus
      POSTGRES_PASSWORD: c3xs1bs$123
      POSTGRES_DB: main
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U primus -d main -h localhost"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - mynetwork
  
  url-shortener-api:    
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    env_file:
      - .envrc
    depends_on:
      db:
        condition: service_healthy
  
  liquibase:
    image: liquibase/liquibase:4.9.1
    container_name: Liquibase_container
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./infrastructure/changelog/:/liquibase/changelog/
    # Command to run the liquibase update service
    command: --defaults-file=/liquibase/changelog/liquibase.properties update
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
    driver: bridge
