// Code generated by MockGen. DO NOT EDIT.
// Source: shortener_service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "urlshortener/model/request"

	gomock "github.com/golang/mock/gomock"
)

// MockShortenService is a mock of ShortenService interface.
type MockShortenService struct {
	ctrl     *gomock.Controller
	recorder *MockShortenServiceMockRecorder
}

// MockShortenServiceMockRecorder is the mock recorder for MockShortenService.
type MockShortenServiceMockRecorder struct {
	mock *MockShortenService
}

// NewMockShortenService creates a new mock instance.
func NewMockShortenService(ctrl *gomock.Controller) *MockShortenService {
	mock := &MockShortenService{ctrl: ctrl}
	mock.recorder = &MockShortenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortenService) EXPECT() *MockShortenServiceMockRecorder {
	return m.recorder
}

// GetOriginalURL mocks base method.
func (m *MockShortenService) GetOriginalURL(context context.Context, url string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalURL", context, url)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetOriginalURL indicates an expected call of GetOriginalURL.
func (mr *MockShortenServiceMockRecorder) GetOriginalURL(context, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalURL", reflect.TypeOf((*MockShortenService)(nil).GetOriginalURL), context, url)
}

// Shorten mocks base method.
func (m *MockShortenService) Shorten(context context.Context, req model.ShortenURLRequest) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shorten", context, req)
	ret0, _ := ret[0].(string)
	return ret0
}

// Shorten indicates an expected call of Shorten.
func (mr *MockShortenServiceMockRecorder) Shorten(context, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shorten", reflect.TypeOf((*MockShortenService)(nil).Shorten), context, req)
}
