// Code generated by MockGen. DO NOT EDIT.
// Source: src/repository/shortener_repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShortenerRepository is a mock of ShortenerRepository interface.
type MockShortenerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShortenerRepositoryMockRecorder
}

// MockShortenerRepositoryMockRecorder is the mock recorder for MockShortenerRepository.
type MockShortenerRepositoryMockRecorder struct {
	mock *MockShortenerRepository
}

// NewMockShortenerRepository creates a new mock instance.
func NewMockShortenerRepository(ctrl *gomock.Controller) *MockShortenerRepository {
	mock := &MockShortenerRepository{ctrl: ctrl}
	mock.recorder = &MockShortenerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortenerRepository) EXPECT() *MockShortenerRepositoryMockRecorder {
	return m.recorder
}

// GetOriginalURL mocks base method.
func (m *MockShortenerRepository) GetOriginalURL(context context.Context, shortenedURL string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOriginalURL", context, shortenedURL)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetOriginalURL indicates an expected call of GetOriginalURL.
func (mr *MockShortenerRepositoryMockRecorder) GetOriginalURL(context, shortenedURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOriginalURL", reflect.TypeOf((*MockShortenerRepository)(nil).GetOriginalURL), context, shortenedURL)
}

// SaveShotenedURL mocks base method.
func (m *MockShortenerRepository) SaveShotenedURL(context context.Context, url, shortenedURL string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveShotenedURL", context, url, shortenedURL)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SaveShotenedURL indicates an expected call of SaveShotenedURL.
func (mr *MockShortenerRepositoryMockRecorder) SaveShotenedURL(context, url, shortenedURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveShotenedURL", reflect.TypeOf((*MockShortenerRepository)(nil).SaveShotenedURL), context, url, shortenedURL)
}
