// Code generated by MockGen. DO NOT EDIT.
// Source: util.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUtil is a mock of Util interface.
type MockUtil struct {
	ctrl     *gomock.Controller
	recorder *MockUtilMockRecorder
}

// MockUtilMockRecorder is the mock recorder for MockUtil.
type MockUtilMockRecorder struct {
	mock *MockUtil
}

// NewMockUtil creates a new mock instance.
func NewMockUtil(ctrl *gomock.Controller) *MockUtil {
	mock := &MockUtil{ctrl: ctrl}
	mock.recorder = &MockUtilMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUtil) EXPECT() *MockUtilMockRecorder {
	return m.recorder
}

// GenerateShortURL mocks base method.
func (m *MockUtil) GenerateShortURL(longURL string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateShortURL", longURL)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateShortURL indicates an expected call of GenerateShortURL.
func (mr *MockUtilMockRecorder) GenerateShortURL(longURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateShortURL", reflect.TypeOf((*MockUtil)(nil).GenerateShortURL), longURL)
}
